### GENERAL SETTINGS ###

# Site settings
title: MindGarage
description: "Ovation MindGarage is an independent 'lab' under the guidance of Marcus Liwicki. It is connected to the teaching activities of Marcus in the area of deep learning, including the lecture 'Very Deep Learning', his supervised projects and theses, and individual studies."
analytics: "UA-86445551-2" #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://mindgarage.de"

# Build settings
markdown: kramdown
permalink: /:categories/:year-:month-:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

# better search engine indexing
gems:
  - jekyll-seo-tag

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  #- title: dribbble
  #  url:
  - title: facebook
    url: https://www.facebook.com/OvationMindGarage/
  - title: twitter
    url: https://twitter.com/mindgarage1
  - title: instagram
    url: https://www.instagram.com/mindgarage/
  #- title: tumblr
  #  url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Rooms 36-(307/309/310),
    - TU Kaiserslautern,
    - Paul-Ehrlich-Str. 36,
    - 67663 Kaiserslautern,
    - Germany
email: liwicki@cs.uni-kl.de 
tel: better write a mail ;)


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Marcus Liwicki
    position: Head
    text:  With the MindGarage I want to offer students a platform to discover and explore DeepLearning.
    img: marcus_team.jpg
    social:
      - title: fa-link
        url: http://blog.mindgarage.de/liwicki/
      - title: envelope #use for email address
        url: mailto:liwicki@cs.uni-kl.de
  - name: Muhammad Zeshan Afzal
    position: Co-founder
    text: MindGarage is a workplace that allows me to convert creative ideas to real application by mentoring the whole process and motivating, inspiring, encouraging, and helping the students as well to explore the area to best of their abilities.
    img: shan_team.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/muhammad-zeshan-afzal-7a8148105
      - title: envelope #use for email address
        url: mailto:afzal@iupr.com
  - name: Ayushman Dash
    position: MS - Computer Science
    text: love for applications of Artificial Intelligence, music and audio production drive me.
    img: ayush_team.jpg
    social:
      - title: linkedin
        url: https://de.linkedin.com/in/ayushman-dash-18a9a4108
      - title: envelope #use for email address
        url: mailto:dash.ayushman.99@gmail.com
  - name: John Gamboa
    position: MS - Computer Science
    text: Iam an insatiable learner, highly curious on new Deep Learning ideas. Hopefully I can quench some of my curiosity with the Mind Garage.
    img: john_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:vaulttech@gmail.com 
  - name: Ingrid Romani
    position: Administrative
    text:  I am glad to support the Mind Garage in all administrative aspects.
    img: ingrid_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:romani@iupr.com
  - name: Dominik Bermühler
    position: Bachelors - Computer Science
    text: For me as a student, the MindGarage offers an awesome startup-like environment where I can discuss and learn about the latest ideas in the field of Deep Learning.
    img: dominik.jpg
    social:
      - title: envelope #use for email address
        url: mailto:d.bermuehler@insiders-technologies.de
  - name: Amit Sahu
    position: MS - Computer Science
    text: I am Amit Sahu -  My (not evil) goal is of creating super-intelligence which surpasses human and machine intelligence.
    img: amit_team.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/amit-sahu-90975212
      - title: envelope #use for email address
        url: mailto:amit.sahu89@gmail.com
  - name: Manabendra Saha
    position: MS - Computer Science
    text: I like changes and change is the only thing constant in my life.
    img: mana_team.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/manabendra-saha-a5b58b17
      - title: envelope #use for email address
        url: mailto:amit.sahu89@gmail.com
  - name: Vinay Chandran Pondenkandath
    position: MS - Computer Science
    text: Hello I am Vinay.</br></br></br>
    img: vinay_team.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/vinaychandranp
      - title: envelope #use for email address
        url: mailto:vinaychandranp@gmail.com
  - name: Johannes Freiermuth
    position: MS - Computer Science / student at Insiders Technologies GmbH
    text: The MindGarage offers us students a very uncomplicated opportunity to run experiments which require the computational power of state of the art equipment.
    img: johannes_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:j.freiermuth@insiders-technologies.de
  - name: Andreas Kölsch
    position: MS - Computer Science / student at Insiders Technologies GmbH
    text: To me the MindGarage is not only a lab which is equipped with excellent  hardware, but also a knowledge hub and a place for discussion. This makes it the perfect place to gain more insights into Deep Learning and AI in general.
    img: andreas_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:a.koelsch@insiders-technologies.de
  - name: Vitor Fortes Rey
    position: Phd candidate at Uni Kaiserslautern / working at DFKI
    text: For me the MindGarage is a place where interesting ideas can meet capable people and hardware.
    img: vitor_team.png
    social:
      - title: envelope #use for email address
        url: mailto:vitorrey@googlemail.com
  - name: Priyamvada Shankar
    position: MS - Computer Science / student at Bayer AG
    text: For someone like me who is deeply interested in understanding various facets of AI and its numerous merits, MindGarage acts as a focal point, providing the infrastructure and atmosphere for like minded people to get together and transform ideas into reality.
    img: priyamvada_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:p_shankar15@cs.uni-kl.de
  - name: Rajveer Shringi
    position: MS - Computer Science
    text: Trying to make this world a better place to live, one day at a time. 
    img: raj.jpeg
    social:
      - title: envelope #use for email address
        url: mailto:rshringi@cs.uni-kl.de
  - name: Rajesh Chidambaram
    position: MS - Cognitive Science
    text: MindGarage is the place to Deep learn ! 
    img: chiddu.jpg
    social:
      - title: envelope #use for email address
        url: mailto:chidamba@rhrk.uni-kl.de
  - name: Vikrant Singh
    position: MS - Computer Science
    text: MindGarage is a cool place to do open minded research
    img: vsingh.jpg
    social:
      - title: envelope #use for email address
        url: mailto:vikrantsing1108@gmail.com
  - name: Soshi Shimada
    position: MS - Computer Science
    text: I like to play with Deep Learning and I found a nice place with a lot of computational power.
    img: soshi.jpg
    social:
      - title: envelope #use for email address
        url: mailto:soshi0928@gmail.com
  - name: Surajit Dey
    position: MS - Computer Science
    text: I want to be a part of Mind Garage because I want to explore the interesting and innovative ideas shared by the Mind Garage Team and at the same time learn about new State of The Art architectures and models that could be implemented in our own projects.
    img: sdey.jpg
    social:
      - title: envelope #use for email address
        url: mailto:s_dey16@cs.uni-kl.de
  - name: Ashutosh Mishra
    position: MS - Computer Science
    text: Go Deep Learning :)
    img: amishra.jpg
    social:
      - title: envelope #use for email address
        url: mailto:ashutosh@cs.uni-kl.de
        
# Supporters information. Shown on About page.
supporters:
  - name: Werner Weiss
    position: CEO of Insiders Technologies GmbH
    text: The MindGarage is an opportunity for the Region of Kaiserslautern
    img: weiss_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:w.weiss@insiders-technologies.de 
  - name: Norbert Wehn
    position: Vice President of the University of Kaiserslautern / Prof. in Microelectronic Systems
    text: The MindGarage is a great and innovative idea for education and research in this important topic.
    img: wehn_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:wehn@eit.uni-kl.de
  - name: Markus Ebbecke
    position: Head of Department at Insiders Technologies GmbH
    text: Deep Learning is a technology which offers amazing opportunities for future business. It is fantastic to see people having an enormous competence working at the MindGarage. They attract other young talents and together they are able to push the limits of technology further. I am very happy about this place as an opportunity in Kaiserslautern.
    img: ebbecke_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:M.Ebbecke@insiders-technologies.de 
  - name: Fotini Simistira
    position: Senior Researcher at University of Fribourg
    text: I love Deep Learning and I love the MindGarage
    img: fotini_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:fotini.simistira@unifr.ch 

        
# Partner information. Shown on Home and About pages.
partners:
  - name: Insiders Technologies
    img: insidersLogo.png
  - name: TU Kaiserslautern
    img: tukl_logo.png

# Short text about your Lab. Shown in footer on every page and also separately on Home and Contact page.
about: "We believe that creativity comes with freedom and to solve challenging problems in AI we need to have freedom and creative thinking. We provide an unconstrained environment to highly motivated students to do whatever that comes to their minds and explore deep learning."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "MindGarage is not an organisation, it is a family. Solving problems, meeting new people, discussing ideas and havining fun is what MindGarage is all about."
    author: Ayushman Dash
    position: Machine Learning Engineer/ Full Stack Web Developer  - MindGarage
    author2: Marcus Liwicki
    position2: apl. Prof. at the University of Kaiserslautern / Head of MindGarage
