### GENERAL SETTINGS ###

# Site settings
title: MindGarage - Deep Learning Lab
description: "MindGarage is the Deep Learning lab at the Kaiserslautern campus of RPTU, headed by Dr. Muhammad Zeshan Afzal. It is a part of the Augmented Vision group at the university and is focused on research in the field of Deep Learning, Computer Vision, and Machine Learning."
analytics: "UA-86445551-2" #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://blog.mindgarage.de"

# Build settings
markdown: kramdown
permalink: /:categories/:year-:month-:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

# better search engine indexing
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Include _pages folder
include: ["_pages"]

### NAVIGATION ###
nav:
  main: # Main navigation
    - title: "Blog"
      url: /blog/
      options:
    - title: "Team"
      url: /team/
      options:
    - title: "Teaching"
      url: /teaching/
      options:
        - title: "Very Deep Learning"
          url: /teaching/very-deep-learning/
        - title: "Seminar and Projects"
          url: /teaching/seminar-and-projects/
        - title: "Theses"
          url: /teaching/theses/
    - title: "Events"
      url: /events/
      options:
        - title: "Mindstorm"
          url: /events/mindstorm/
        - title: "Ovation Summer Academy"
          url: /events/ovation-summer-academy/
    - title: "Publications"
      url: /publications/
      options:
    - title: "Contact"
      url: /contact/
      options:

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  #- title: dribbble
  #  url:
  - title: facebook
    url: https://www.facebook.com/OvationMindGarage/
  - title: twitter
    url: https://twitter.com/mindgarage1
  - title: instagram
    url: https://www.instagram.com/mindgarage/
  #- title: tumblr
  #  url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
      - Gottlieb-Daimler-Str. 48 (48-462),
      - 67663 Kaiserslautern
      - Germany
email: afzal.tukl@gmail.com

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  # Administrative
  - name: Muhammad Zeshan Afzal
    type: faculty
    position: Current Head / Co-Founder
    img: shan_team.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/muhammad-zeshan-afzal
      - title: envelope #use for email address
        url: mailto:muhammad_zeshan.afzal@dfki.de
  - name: Didier Stricker
    type: faculty
    position: "" # TODO: add position
    img: didier_team.png
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/didier-stricker-20520530
      - title: envelope #use for email address
        url: mailto:didier.stricker@dfki.de

  # PhD Students
  - name: Khurram Azeem Hashmi
    type: phd
    position: PhD - Computer Science
    img: https://media.licdn.com/dms/image/C4D03AQHD4dF5b6SXwQ/profile-displayphoto-shrink_800_800/0/1584713987401?e=2147483647&v=beta&t=9ajFlCIpXsciO0WEXEAJbaxOr90waCrIpYOB7qVnmuc
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/khurramhashmi
      - title: envelope #use for email address
        url: mailto:khurram_azeem.hashmi@dfki.de
  - name: Tahira Shehzadi
    type: phd
    position: PhD - Computer Science
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/tahira-shehzadi-a9022812b
      - title: envelope #use for email address
        url: mailto:tahira.shehzadi@dfki.de
  - name: Muhammad Saif Ullah Khan
    type: phd
    position: PhD - Computer Science
    img: https://github.com/saifkhichi96.png
    social:
      - title: globe
        url: https://www.saifkhichi.com/
      - title: linkedin
        url: https://www.linkedin.com/in/saifkhichi96
      - title: github
        url: https://www.github.com/saifkhichi96
      - title: envelope #use for email address
        url: mailto:muhammad_saif_ullah.khan@dfki.de

  # Research Assistants
  - name: Sheikh Talha Uddin
    type: hiwi
    position: Research Assistant
  - name: Sankalp Sinha
    type: hiwi
    position: Research Assistant
  - name: Muhammad Ahmed Ullah Khan
    type: hiwi
    position: Research Assistant
  - name: Saad Najib
    type: hiwi
    position: Research Assistant

  # Alumni (Administrative)
  - name: Marcus Liwicki
    type: alumni
    position: Former Head / Founder
    img: marcus_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:liwicki@cs.uni-kl.de
  - name: Ingrid Romani
    type: alumni
    position: Administrative
    img: ingrid_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:romani@iupr.com

  # Alumni (PhD Students)
  - name: John Gamboa
    type: alumni
    position: PhD - Linguistics
    img: john_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:vaulttech@gmail.com
  - name: Vitor Fortes Rey
    type: alumni
    position: PhD - Embedded Intelligence
    img: vitor_team.png
    social:
      - title: envelope #use for email address
        url: mailto:vitorrey@googlemail.com

  # Alumni (Master Students)
  - name: Ayushman Dash
    type: alumni
    position: Researcher (Insiders Technologies GmbH)
    img: ayush_team.jpg
  - name: Kumar Shridhar
    type: alumni
    position: MS - Computer Science
    img: shridhar_team.jpg
  - name: Sidney Pontes-Filho
    type: alumni
    position: MS - Computer Science
    img: sidney_team.jpg
  - name: Dominik Bermühler
    type: alumni
    position: MS - Computer Science
    img: dominik.jpg
  - name: Amit Sahu
    type: alumni
    position: MS - Computer Science
    img: amit_team.jpg
  - name: Saurabh Varshneya
    type: alumni
    position: MS - Computer Science
    img: saurabh_team.jpg
  - name: Manabendra Saha
    type: alumni
    position: MS - Computer Science
    img: mana_team.jpg
  - name: Abhash Sinha
    type: alumni
    position: MS - Computer Science
    img: abhash_team.jpg
  - name: Vinay Chandran Pondenkandath
    type: alumni
    position: MS - Computer Science
    img: vinay_team.jpg
  - name: Ashutosh Mishra
    type: alumni
    position: MS - Computer Science
    img: ashu_team.jpg
  - name: Priyamvada Shankar
    type: alumni
    position: MS - Computer Science (Bayer AG)
    img: priyamvada_team.jpg
  - name: Johannes Freiermuth
    type: alumni
    position: MS - Computer Science (Insiders Technologies GmbH)
    img: johannes_team.jpg
  - name: Andreas Kölsch
    type: alumni
    position: MS - Computer Science (Insiders Technologies GmbH)
    img: andreas_team.jpg
  - name: Rajveer Shringi
    type: alumni
    position: MS - Computer Science
    img: raj.jpeg
  - name: Rajesh Chidambaram
    type: alumni
    position: MS - Cognitive Science
    img: chiddu.jpg
  - name: Vikrant Singh
    type: alumni
    position: MS - Computer Science
    img: vsingh.jpg
  - name: Soshi Shimada
    type: alumni
    position: MS - Computer Science
    img: soshi.jpg
  - name: Sadique Siddiqui
    type: alumni
    position: MS - Computer Science
    img: sadique_team.jpg
  - name: Surajit Dey
    type: alumni
    position: MS - Computer Science
    img: sdey.jpg
  - name: Shailza Jolly
    type: alumni
    position: MS - Computer Science
    img: shailza_team.jpg
  - name: Asif Irfan
    type: alumni
    position: MS - Computer Science
    img: asif_team.jpg

  # Alumni (Bachelor Students)
  - name: Purvanshi Mehta
    type: alumni
    position: Bachelors - Computer Science
    img: purvanshi_team.jpg
    social:
      - title: fa-link
        url: http://purvanshi.github.io
      - title: envelope #use for email address
        url: mailto:purumehta69@gmail.com

# Supporters information. Shown on About page.
supporters:
  - name: Marcus Liwicki
    position: Professor at Luleå University of Technology, Sweden
    img: marcus_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:liwicki@cs.uni-kl.de
  - name: Werner Weiss
    position: CEO of Insiders Technologies GmbH
    img: weiss_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:w.weiss@insiders-technologies.de
  - name: Norbert Wehn
    position: Vice President of the University of Kaiserslautern (2013-2017)/ Prof. in Microelectronic Systems
    img: wehn_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:wehn@eit.uni-kl.de
  - name: Markus Ebbecke
    position: Head of Department at Insiders Technologies GmbH
    img: ebbecke_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:M.Ebbecke@insiders-technologies.de
  - name: Fotini Simistira
    position: Senior Researcher at University of Fribourg
    img: fotini_team.jpg
    social:
      - title: envelope #use for email address
        url: mailto:fotini.simistira@unifr.ch

# Partner information. Shown on Home and About pages.
partners:
  - name: Insiders Technologies
    img: insidersLogo.png
    url: https://insiders-technologies.de
  - name: TU Kaiserslautern
    img: tukl_logo.png
    url: https://www.uni-kl.de

# Short text about your Lab. Shown in footer on every page and also separately on Home and Contact page.
about: "At MindGarage, we believe that creativity and innovation are essential for advancing the field of Artificial Intelligence. That's why we provide an open and unconstrained environment for highly motivated students to explore the possibilities of Deep Learning. We encourage freedom of thought and creativity in tackling challenging problems, and we're always on the lookout for talented individuals to join our team. If you're passionate about AI and want to contribute to groundbreaking research in Deep Learning, we invite you to learn more about our lab and our projects."
